---
title: Leopardi em Lígua Portuguesa
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
baseurl: "/leopardi"
author: Andréia Guerini / Avelar Fortunato /
email: 
description: Grupo de estudos em Leopardi em Lígua Portuguesa
exclude:
- README.md
- Gemfile.lock
- vendor
